New Chart: Sparkline Chart
abcnews/dailygraphics pull request #79
Opened 2017-06-16 02:08 UTC by phocks

I believe this chart is probably just about ready to deploy. I think I've made all the proper changes necessary. @drzax if you could just check if there's anything I've missed, that would be great. Also it was saying it could automatically merge before, but now it's saying it can't...

A demo of the sparklines can be seen here: http://sparkline.surge.sh/

If these are approved I'll move on to the next steps. I've already created the Google Doc template and updated id in graphic_config.py

2017-06-16 07:16 UTC, AshKyd commented
Looking good, but let's go through it together on Monday.

2017-06-19 04:51 UTC, AshKyd requested changes

2017-06-19 04:51 UTC, AshKyd commented on graphic_templates/sparkline_chart/css/graphic.less
> +@media screen and (min-width: 500px) {
We can probably remove this since it's not doin' nothin'

2017-06-19 04:51 UTC, AshKyd commented on graphic_templates/sparkline_chart/js/graphic.js
> +                    tooltipCircle.style('visibility', 'visible')
No semicolons 😱

2017-06-19 04:51 UTC, AshKyd commented on graphic_templates/sparkline_chart/js/graphic.js
> +            minMaxValueLabel.html(
This doesn't sanitise inputs (eg. ampersands, script tags)

2017-06-19 06:36 UTC, phocks commented on graphic_templates/sparkline_chart/css/graphic.less
> +@media screen and (min-width: 500px) {
Gone!

2017-06-19 06:37 UTC, phocks commented on graphic_templates/sparkline_chart/js/graphic.js
> +                    tooltipCircle.style('visibility', 'visible')
Oh nooooo! Fixed now 😅

2017-06-19 06:38 UTC, phocks commented on graphic_templates/sparkline_chart/js/graphic.js
> +            minMaxValueLabel.html(
No more .html methods any more 💯

2017-06-19 11:10 UTC, AshKyd approved these changes

2017-06-27 23:08 UTC, merged